### ISSUE TITLE
Clear history clears "disable flash on youtube" setting

### ISSUE THREAD

**Issue by klemens** [klemens/ff-youtube-all-html5#16]
When clearing the history with the option "Site Preferences" enabled, the site specific setting for disabling flash on youtube gets reset.

~~At least we have to listen for the clear history event to reset the checkbox in the settings~~. *This has already been done since the beginning… (f2d8fd2a24f81b4302badceae767a63ca8c6b15a)* We additionally could remember its state internally and restore it after the clear history event, but I am not yet sure if this is appropriate.

**Comment by buuf** [comment]
I'd rather it be remembered internally, given the state of flash right now. In some instances, it doesn't work period for me at least.

**Comment by klemens** [comment]
I could of course save this internally and set it on startup if it has changed.
The problem I have with this is that I then in some sense ignore the users privacy by forcing the value, although the user decided to delete all site preferences. What do you think?

**Comment by buuf** [comment]
I would think other options you save internally do the same thing. At the very least you could create an option to save all settings internally or on a per session basis.

**Comment by klemens** [comment]
I am still not convinced that overwriting the users intention to delete their site preferences by silently restoring the one for flash on youtube is the way to go.
Fortunately this setting is no longer really important, as the new default video loading method (Force HTML5-Test) will load the HTML5 player even on old firefox versions when flash is installed and enabled.
