### ISSUE TITLE
Auto hide annotations

### ISSUE THREAD

**Issue by homlett** [klemens/ff-youtube-all-html5#21]
Great add-on, thanks! What do you think about to add an option to auto hide annotations on youtube videos?

**Comment by Krysisx** [comment]
+1 for this enhancement

**Comment by klemens** [comment]
f8a8ab78403d560b9811f2ef39e0d0b2ce27b71c adds a new experimental option to hide annotations. It will be part of version 3.1.0, which will be released in a few days.
