### ISSUE TITLE
Extend autoplay options to allow foreground video

### ISSUE THREAD

**Issue by tumpio** [klemens/ff-youtube-all-html5#22]
The current implementation #17 allows to pause or play all videos at start.
I would like to see an option to only pause videos that are loaded as background tabs and auto play foreground videos.

And thank you for creating this extension! :)

**Comment by klemens** [comment]
This has been implemented in 852fde6c2ef8baeb5fac4eb9c0b898cee35e5955, which is part of [v3.1.0-beta3](https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.1.0-beta3).
