### ISSUE TITLE
Videos not autoplaying

### ISSUE THREAD

**Issue by barrybeefcurtains** [klemens/ff-youtube-all-html5#25]
Certain videos just don't autoplay, no idea why but when I disable the addon they play like usual so I know it's the addon and not anything else.
To get past this problem I have to pause the video and unpause it again or press the HTML 5 button, then it works fine but this is annoying for playlists. Its only just started happening, started about a week ago maybe.

**Comment by klemens** [comment]
I am closing the two year old bug.

If you are still using the add-on and are experiencing the same problem, please reopen!
