### ISSUE TITLE
Set default playback speed at start of video

### ISSUE THREAD

**Issue by klemens** [klemens/ff-youtube-all-html5#32]
This was suggested in an E-Mail by James Pace and should be doable using the standard youtube api (`player.setPlaybackRate()`).
Would anyone else use this?

**Comment by SmurgBurglar** [comment]
i would love this

**Comment by klemens** [comment]
This has been implemented in 8494334d6bf0065c8fb3f1b04be3a8649fe2eb5f which will be part of the next release.
