### ISSUE TITLE
Don't disable autostart in case of playlists

### ISSUE THREAD

**Issue by aef** [klemens/ff-youtube-all-html5#46]
If playing a playlist on YouTube, I think it might be better not the disable the autostart, or make that a separate setting. Usually, when I use a playlist, my intention is to see everything there in a row. Would be really cool to have that option again.

**Comment by klemens** [comment]
This has been implemented in bf3d0aff74c328706d28a6ebb94360e2ce8b8f45, which is especially useful in combination with a5772c429ee2f90a48137234cfc997c6fe292e5e (open the video without the playlist from a playlist link). Both are part of [v3.1.0-beta3](https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.1.0-beta3).
