### ISSUE TITLE
Add support for embedded youtube videos in G+

### ISSUE THREAD

**Issue by Siedlerchr** [klemens/ff-youtube-all-html5#48]
First of all, thanks for the nice plugin, it is really really good.

A nice feature would be, to enable html5 for youtube also in Google+, currently it always wants to enable flash player. But, if html5 player is enabled as default player, in G+ the html5 player is also used.
https://www.youtube.com/html5

Enable html5 default player at the site above, then open this link and play the embedded video.
https://plus.google.com/107447833844645630113/posts/Pe1E95B3py8

Best Regards
Siedlerchr

**Comment by klemens** [comment]
This will be fixed in version 2.2.0, also see discussion in #40.

**Comment by klemens** [comment]
This is now fixed and will be in the next alpha or beta. See 3a69da4643e0592b7871bb0823ab211b6103fe1d and #40.
