### ISSUE TITLE
Disable youtube autoplay for consecutive videos

### ISSUE THREAD

**Issue by apfelchips** [klemens/ff-youtube-all-html5#50]
Some time ago youtube changed the default behavior to automatically play the next video from the recommended sidebar when the one you just watched is over, since there is already the option to disable autoplay completely with this extension, could you please consider to make an option to only disable the autoplay of consecutive videos?

thanks!

**Comment by klemens** [comment]
Hm, there is already a button on youtube with which you can disable this kind of autoplay. Or do you want something else?

**Comment by apfelchips** [comment]
just to be clear we are talking about the same button/feature:  ![bttn](https://cloud.githubusercontent.com/assets/6919384/7471796/8ba4e058-f32b-11e4-8d0b-7a977a394ffb.png)

the problem with it is that your setting doesn't stay put and defaults to the Autoplay behavior, so I have to change again in every new browser session, which is bugging me, because I want to watch the video I clicked on and nothing else after that.

At risk of bloating the addon like YouTubeCenter did an autoloop feature, selectable via the top corner button, would be nice to have.

**Comment by klemens** [comment]
The status of this button gets saved in the PRFE-Cookie. It seems that this cookie gets deleted because of your firefox settings.
I just implemented a new module (CookieChanger) which should make it relatively easy to disable autoplay for people who  have cookies disabled or use some kind of private browsing.

I opened another issue for your replay suggestion: #53

**Comment by klemens** [comment]
This is now implemented in f6179d7d055ea32376677a6560a2bfa342266243, which will be part of verion 3.1.0.
It works fine for me, however I am not sure if it will always work, therefore it is marked as experimental.
