### ISSUE TITLE
Not working anymore on new youtube, sound play but no video

### ISSUE THREAD

**Issue by mcdodge34** [klemens/ff-youtube-all-html5#55]
Just to report an issue here, your awesome plugin doesn't work correctly anymore, when the plugin is activated I only have sound and a black screen on any Youtube videos, when I disable it, it works fine. I need your awesome work to make sure stupid youtube doesn't play videos in 240-360p and doesn't start videos automatically (I hate that so much, I let them preload a little bit)

**Comment by klemens** [comment]
Does this problem also occur with the newest beta? https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.0.0beta1

**Comment by BogusLogin** [comment]
Hi, I encountered the same problem today. I installed the version you proposed and it seems to work for now! ty

**Comment by klemens** [comment]
Thanks for your comment! I have just created a [new stable version](https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.0.0) and uploaded it to mozilla addons. Unfortunately it has be reviewed before it will be available via auto-update.

**Comment by mcdodge34** [comment]
Sorry about being late for responding, I had a emergency call (I'm a PC tech support) I'll test the new beta real soon.

**Comment by mcdodge34** [comment]
Works, but the videos are not paused on load anymore, minor annoyance that would be really appreciated if you could fix that since now I'm not 100% sure your plugin works or not anymore, it changes the resolution at least.

**Comment by klemens** [comment]
No problem. :wink:
I will fix the prevent autostart feature with the next release, see #33.

**Comment by mcdodge34** [comment]
Any ways to be notified when a new release is out, the auto-update of plugins never really worked for my Firefox, I have to check manually every single time.

**Comment by klemens** [comment]
There are two feeds, one from the mozilla addon page: https://addons.mozilla.org/de/firefox/addon/youtube-all-html5/versions/format:rss
The other one from github: https://github.com/klemens/ff-youtube-all-html5/releases.atom

Generally they should be in sync, although sometimes a beta might be on github, but not on mozilla addons.
