### ISSUE TITLE
Thumbs up/down buttons in full screen

### ISSUE THREAD

**Issue by mgalyean** [klemens/ff-youtube-all-html5#56]
This is not a bug per se, but given the feature exists in the flash player, it does seem to be missing functionality.  Would there be any way to code in thumbs up/down buttons in html5 player when in full screen via ff-youtube-all-html5?  I've given up trying to get a response from the youtube team about this so found myself here.  In the flash player I used these buttons all the time to give kudos to great youtube vids but when watching a queue of vids in html5 it is just too much hassle to exit full screen (before the next vid starts!) just to hit that thumbs up button.  Does the html5 player API that JS and plug-ins can use allow these buttons?

**Comment by klemens** [comment]
Sorry for the late response, I somehow overlooked your issue.

While it would technically be possible to add such a button to the player, I don't think this would be a good fit for my addon. I always try to do as few modifications of the player as possible. (apart from changing it's size, which is already breaking regularly)
An alternative might by some sort of keybinding, what do you think? I would also have to look at how the fullscreen mode really works, a it seems the page is reload only after you leave fullscreen again.
