### ISSUE TITLE
Force HTML5-test not set as default

### ISSUE THREAD

**Issue by forteller** [klemens/ff-youtube-all-html5#57]
Hey, love the extension! 

But I've noticed on both the PC's I've installed it on that "Emulate IE" was set as the default loading method, not "Force HTML5-test", even though that's the one that says it's supposed to be default (and should be default to not give IE better statistics than it should. With fewer people using Firefox now than before, it's even more important to not emulate other browsers, but give the right info for the stats)

Thanks!

**Comment by klemens** [comment]
You are right, thought I had already done that, but apparently the IE-emulation is still the default. (https://github.com/klemens/ff-youtube-all-html5/blob/master/package.json#L101)
I will change this to HTML5-test (or none for newer firefox versions) in the next release.

**Comment by klemens** [comment]
This has been fixed in 63807a625ca8e787eb6cdb16ad39e9858597e387, which will bei in version 3.0.3, which ich currently in the review queue at mozilla. (see #58)
