### ISSUE TITLE
Makes Youtube think it's an out-of-date version of IE

### ISSUE THREAD

**Issue by blakjaknz** [klemens/ff-youtube-all-html5#58]
See https://www.reddit.com/r/firefox/comments/43wgf6/why_does_youtube_think_im_running_an_outofdate/

Have had to disable the plugin to resolve the above. See also https://www.reddit.com/r/firefox/comments/439pp0/youtube_and_firefox/

**Comment by klemens** [comment]
Yup, there is already an option in the settings to turn off the IE emulation. It was also already planned to change this in the next version (#57), but now that youtube shows this warning, I will probably release an updated version tomorrow.

**Comment by klemens** [comment]
This is fixed with 63807a625ca8e787eb6cdb16ad39e9858597e387. The new version 3.0.3 is currently in the review queue at addons.mozilla.org.
