### ISSUE TITLE
Embedded video with /v/ in the url uses flash

### ISSUE THREAD

**Issue by dyskette** [klemens/ff-youtube-all-html5#59]
This url uses flash https://www.youtube.com/v/Xs3cpELeS04?enablejsapi=1?api=1

As found here http://www.taringa.net/Dyskette/mi/qVEOt

If you cannot access it, this is the iframe...

``` html
<iframe src="https://www.youtube.com/v/Xs3cpELeS04?enablejsapi=1?api=1" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" width="594px" frameborder="0" height="400px"></iframe>
```

**Comment by klemens** [comment]
Yes, the`v` urls always use the flash player. You can replace the `v` with `embed` to get the HTML5 player, however I am not yet sure if we should do this automatically, as this might break websites that expect the flash player.
I will take a look at it for the next release, but I cannot promsie anything.

**Comment by klemens** [comment]
To be more specific, automatically changing the uri when it is used in an iframe will probably work in most places, but it will break websites that use the object tag to embed the flash applet directly and don't specify a embed fallback tag.

**Comment by klemens** [comment]
Turns out, this (replacing `/v/` with `/embed/`) is exactly what firefox does by default starting with 47: https://bugzilla.mozilla.org/show_bug.cgi?id=769117
This is controlled by the `plugins.rewrite_youtube_embeds` setting which should be enabled by default.
