### ISSUE TITLE
video resolution BUG!

### ISSUE THREAD

**Issue by Thugfish** [klemens/ff-youtube-all-html5#60]
I just select to load with 1080p i have tried with 720p too but nothing happens fix this please

**Comment by klemens** [comment]
What resolutions are shown directly in the youtube interface? Are you using the HTML5 player (right click the player, can be forced using the addon options).
Does this occur with every video?

**Comment by klemens** [comment]
I am closing this since there hasn't been a reaction for over half a year.
Please reopen the issue if you still have problems!
