### ISSUE TITLE
Dev Version

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [klemens/ff-youtube-all-html5#61]
Could it be possible for you to make a dev version, a unlisted version installable using github or gitlab (version check is possible on it)

**Comment by klemens** [comment]
I added a new beta version as a pre-release. I also uploaded it to [amo](https://addons.mozilla.org/firefox/addon/youtube-all-html5/versions/beta). The advantage is, that you will get future betas automatically.

**Comment by ZatsuneNoMokou** [comment]
Beta version can be signed? Good to know ^^

**Comment by klemens** [comment]
Yup, as long as it passes the automatic review. :wink:

**Comment by ZatsuneNoMokou** [comment]
Thanks
