### ISSUE TITLE
That autoplay setting is not working for me.

### ISSUE THREAD

**Issue by TeoTwawki** [klemens/ff-youtube-all-html5#63]
Using version 3.1.0 on Firefox 50.0.2, I have "prevent autoplay of recommended videos" checked, but they are still playing anyway. I am not looking at a playlist either. The autoplay is showing checked in youtube and when the video ends it auto loads the next recommended one..so I still have to uncheck it on their site.

This one feature is the entire reason I have the add-on installed, since screwtube likes to default the autoplay to "on" anytime the cookies are cleared or I am not logged in.

**Comment by klemens** [comment]
You are right, I just tested the feature and it doesn't work anymore. I will have a look asap!

**Comment by TeoTwawki** [comment]
Thanks :)

**Comment by klemens** [comment]
This should be fixed with 4a56b2533292c810078f49f1f19210250156c225. Could you please test the new beta version [3.1.1-rc1](https://addons.mozilla.org/firefox/addon/youtube-all-html5/versions/3.1.1-rc1)?

**Comment by TeoTwawki** [comment]
Appears to be working as expected now. Thanks again!
