### ISSUE TITLE
Skip button in ADs missing

### ISSUE THREAD

**Issue by enricotagliavini** [klemens/ff-youtube-all-html5#67]
I recently switched to "YouTube ALL HTML5", I don't block ADs on youtube and I noticed the SKIP button that normally appears after 5 seconds is missing. I can use the "force playback" in the addon menu to get around this but it's way less convenient. It's under a menu and the button to open it is tiny. There is nothing wrong with the size of the button, it should not be intrusive. However not being able to skip the AD right away from the video interface with the normal button is annoying.

**Comment by klemens** [comment]
This issue *should* be fixed in the new version [3.1.2-beta1](https://addons.mozilla.org/firefox/addon/youtube-all-html5/versions/3.1.2-beta1). Could you test if this works for you?

**Comment by enricotagliavini** [comment]
I've installed it, but am having an hard time finding a video with a video AD. Possibly this is because I'm in a different country compared to usual (I'm on vacation right now). I'll let you know as soon as I get one.

For the time being, thank you.

**Comment by enricotagliavini** [comment]
I can confirm this issue if fixed with 3.1.2-beta1. Thank you.
