### ISSUE TITLE
Controlling the progress bar from the Numeric keypad, Number 1 is missing!

### ISSUE THREAD

**Issue by Midoweimar** [klemens/ff-youtube-all-html5#68]
Controlling the progress bar from the Numeric keypad (on the right side of the keyboard) works only for 2 through 9 and 0. Number 1 does not work. Great Add-On by the way!

**Comment by klemens** [comment]
Interesting find. But this seems to be a youtube bug, because `1` also doesn't work if the add-on is disabled.
