### ISSUE TITLE
End of "classic" addons

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [klemens/ff-youtube-all-html5#69]
Firefox 57 is announced as the end of  the classic Firefox addon (lol, so much problems remaining, they are smart), do you have any plan for it or will you stop your addon?

**Comment by klemens** [comment]
I think most of the add-on should be possible as a WebEx, except the option to disable the flash plugin only for youtube. However, someone has to port it, and currently I don't have the time needed.

**Comment by ZatsuneNoMokou** [comment]
I see, I understand, I don't have much time too. (I already don't install Flash anymore)
